version: '3.3'

services:

  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: user
      POSTGRES_DB: database
    restart: always
    logging:
      driver: none

  app:
    depends_on:
      - db
    build: .
    ports:
    - "8000:8000"
    restart: always
    environment:
      DB_NAME: database
      DB_USER: user
      DB_PASSWORD: '123456'
      DB_HOST: db
      FLASK_ENV: development

volumes:
  db_data: {}